apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoraforcollege-deployment
  labels:
    app: quoraforcollege
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quoraforcollege
  # The template section is configuration file in itself but it is configurations for pod as pod needs to have it's seperate configurations
  template:
    metadata:
      labels:
        app: quoraforcollege
    spec:
      conainers:
      - name: quoraforcollege_depl
      # You need to add the container registry published image link here
        image: quoraforcollege_container
        ports:
        - containerPort: 8080